// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBmwGusFE-fP9-MkR8THpUNv0281HMmecE',
    appId: '1:749557276425:web:6c13f4ec178a97e6703dd8',
    messagingSenderId: '749557276425',
    projectId: 'disaster-response-app-7a864',
    authDomain: 'disaster-response-app-7a864.firebaseapp.com',
    storageBucket: 'disaster-response-app-7a864.firebasestorage.app',
    measurementId: 'G-ZGHHWXDG66',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDjrAxPNRdOP0Te3_cfQZRCch_iSgv7NEc',
    appId: '1:749557276425:android:93e0155dc4f2059b703dd8',
    messagingSenderId: '749557276425',
    projectId: 'disaster-response-app-7a864',
    storageBucket: 'disaster-response-app-7a864.firebasestorage.app',
  );

}